import {
  Admin,
  AffiliatedSchoolList,
  AffilliationUpgrade,
  AffliatedSchools,
  Approval,
  CVE,
  Circular,
  Dashboard,
  DespatchDetails,
  DisaffiliatedSchools,
  Graduations,
  GstInvoice,
  GstTransaction,
  ICSE,
  ISC,
  Inspectors,
  Masters,
  MyMenu,
  Notification,
  Payment,
  PaymentByCategory,
  PaymentRecieved,
  PeriodicInspection,
  PermanentAffliation,
  PermanentAffliationForm,
  ProvisionalAffilliation,
  ProvisionalAffilliationForm,
  Report,
  SchoolBankDetails,
  Search,
  Setting,
  SubjectionAddition,
  Tasks,
  Training,
  UpgradeAffilliationForm,
} from "../../Assets/Icon/Icons";

export const NavIcons = {
  tasks: Tasks,
  notifications: Notification,
  circulars: Circular,
  dashboard: Dashboard,
  icse: ICSE,
  isc: ISC,
  cve: CVE,
  search: Search,
  report: Report,
  masters: Masters,
  payment: Payment,
  settings: Setting,
  admin: Admin,
  provisional_affiliation_requests: ProvisionalAffilliation,
  upgrade_affiliation_requests: AffilliationUpgrade,
  permanent_affiliation_requests: PermanentAffliation,
  provisional_affiliation_forms: ProvisionalAffilliationForm,
  upgrade_affiliation_forms: UpgradeAffilliationForm,
  permanent_affiliation_forms: PermanentAffliationForm,
  affiliated_schools: AffliatedSchools,
  graduations: Graduations,
  approval_of_periodic_updates: Approval,
  list_of_affiliated_schools: AffiliatedSchoolList,
  subject_addition: SubjectionAddition,
  disaffiliated_schools: DisaffiliatedSchools,
  periodic_inspection: PeriodicInspection,
  inspectors: Inspectors,
  payments_to_be_recieved: PaymentRecieved,
  payments_by_category: PaymentByCategory,
  school_bank_details: SchoolBankDetails,
  gst_transaction_list: GstTransaction,
  gst_invoice_list: GstInvoice,
  training_program: Training,
  my_menu: MyMenu,
  despatch_details: DespatchDetails,
};
