export const UPDATE_PAGE_SIZE = "UPDATE_PAGE_SIZE";
export const UPDATE_PAGE_LENGTH = "UPDATE_PAGE_LENGTH";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
